### ISSUE TITLE
What and When to Log?

### ISSUE THREAD

**Issue by nathanheffley** [dealerinspire/laravel-operations#5]
What kind of logging would be useful?

Some main areas where I could see information being logged:
1. When Operation is put into the queue
2. When Operation starts to run
3. When Operation is stopped or canceled
4. When Operation is finished

**Comment by fredjiles** [comment]
it would be kind of cool maybe to have a logger that was operation specific.  Not sure how magic it would be to know which operation was the current context but to be able to do something like `operation->log('something happened')` then it could be generic. 

I do for sure think you need at minimum the 4 you listed above.  Is there a difference between "put into queue" and "scheduled"?  IE I want it to run every 2 hours so it should be queued at 12:25 but it actually gets added to the queue at 12:26?

**Comment by nathanheffley** [comment]
Yes, there is a difference between when an operation is scheduled (the value in the `should_run_at` column) and when an operation is placed into the queue. If you have your scheduler set to run every minute then the discrepancy will only be up to almost a minute, but if you have it set to 10 minutes, for example, that discrepancy could be anywhere from 1 second to almost 10 minutes.

I like the idea of being able to customize how different operations log. It could just log to the standard info log defined in the `.env` if not set. If it is overridden then it would call the operation's `log` function.

**Comment by nathanheffley** [comment]
After thinking about this more, I think it is up to the implementation to determine when to log. It is easy to log whenever you schedule an operation (just do it side-by-side), there is a `queue` function already implemented that could be used for logging when it is put into the queue, and then once it is running any logs can be in the `run` function that must be implemented anyway.
